- name: install apache and php
  tags: apache,php,httpd
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change email address for admin (Rocky)
  tags: apache,httpd,rocky
  lineinfile: # module to modify a line in a file
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin' # regular expression to find the line to be modified
    line: ServerAdmin anthony@server4 # text of the new line
  when: ansible_distribution == "Rocky"
  notify: restart_apache # notify this handler if something changes

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy: # module for copyng files
    src: default_site.html # source file
    dest: /var/www/html/index.html  # destination file
    owner: root # user that owns the file
    group: root
    mode: 0644 # set file permissions
