---

- hosts: all
  become: true
  tasks:

  - name: update repo index and install apache and php
    apt:
      name:
        - "{{ apache_pkg }}" # these are variables
        - "{{ php_pkg }}"
      state: latest
      update_cache: yes

