---

- hosts: all
  become: true
  tasks:

  - name: update repo index and install apache and php
    package: # using package for ansible to detect whether to use apt or dnf
      name:
        - "{{ apache_pkg }}" # these are variables
        - "{{ php_pkg }}"
      state: latest
      update_cache: yes

