---

- hosts: all
  become: true
  pre_tasks: # pre_tasks mandates that this section gets executed first, although it has no effect in our script since it is at the beginning of it

  - name: install updates (Ubuntu)
    tags: always # this will always be executed
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Rocky)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php (Ubuntu)
    tags: apache,apache2,php,ubuntu # different tags, comma separated with no spaces
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache (httpd) and php (Rocky)
    tags: apache,httpd,php,rocky
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy: # module for copyng files
      src: default_site.html # source file
      dest: /var/www/html/index.html  # destination file
      owner: root # user that owns the file
      group: root
      mode: 0644 # set file permissions 


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb (mariadb-server) (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb (Rocky)
    tags: db,mariadb,rocky
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba  (Ubuntu or Rocky)
    tags: samba,ubuntu,rocky
    package:
      name: samba # this package has the same name in both distributions so it can all be done in one task
      state: latest
