---

- hosts: all
  become: true
  pre_tasks: # pre_tasks mandates that this section gets executed first, although it has no effect in our script since it is at the beginning of it

  - name: update repo cache (Ubuntu)
    tags: always # this will always be executed
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update repo cache (Rocky)
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
